config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "records#index"
  resources :records, only: [:index ,:new ,:create]


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/form/base.rb
class Form::Base
  include ActiveModel::Model
  include ActiveModel::Callbacks
  include ActiveModel::Validations
  include ActiveModel::Validations::Callbacks

end

app/models/form/record_collection.rb
class Form::RecordCollection < Form::Base
  FORM_COUNT = 2
  attr_accessor :records, :user_id

  def initialize(attributes = {})
    super attributes
    self.records = FORM_COUNT.times.map { Record.new() } unless self.records.present?
  end

  def records_attributes=(attributes)
    # self.records = attributes.map { |_, v| Record.new(v) }
    self.records = attributes.map { |_, v| Record.new(v.merge(user_id: user_id)) }
  end

  def save
    Record.transaction do
      self.records.map do |record|
        if record.availability
          record.save
        end
      end
    end
     return true
    rescue => e
     return false
  end
end

app/models/record.rb
class Record < ApplicationRecord
  validates :recorded_at, presence: true
  validates :spending_way_id, presence: true, numericality: { other_than: 1, message: "を選択してください。" }
  validates :spending_pay_id, presence: true, numericality: { other_than: 1, message: "を選択してください。" }
  validates :price, presence: true,numericality: { only_integer: true }
  validates :availability, inclusion: { in: [true, false] }, presence: true

  belongs_to :user

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :spending_way
  belongs_to_active_hash :spending_pay
end

app/models/spending_pay.rb
class SpendingPay < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '現金' },
    { id: 3, name: 'カード' },
    { id: 4, name: 'その他' }
  ]

  include ActiveHash::Associations
  has_many :records
end

app/models/spending_way.rb
class SpendingWay < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '食費' },
    { id: 3, name: '生活費' },
    { id: 4, name: '医療費' },
    { id: 5, name: '衣類' },
    { id: 6, name: 'その他' }
  ]

  include ActiveHash::Associations
  has_many :records
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname,presence: true
  validates :password,
            format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i }

  has_many :records
  # accepts_nested_attributes_for :records
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?


  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,keys: [:nickname])
  end

  def after_sign_in_path_for(resource)
    new_record_path
  end

end

app/controllers/records_controller.rb
class RecordsController < ApplicationController

  def index
  end

  def new
    @form = Form::RecordCollection.new
  end

  def create
    
    @form = Form::RecordCollection.new(record_collection_params)
    # binding.pry
    if @form.save
      redirect_to new_record_path
    else
      render :new
    end
  end

  private

  def record_collection_params
    params
    .require(:form_record_collection)
    .permit(records_attributes: [:recorded_at, :spending_way_id, :spending_pay_id, :price, :description, :user_id])
    .merge(user_id: current_user.id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KakeboPracD</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/records/index.html.erb
<div class='top-page'>
  <div class='top-main-contents'>
      <div class='top-main-contents-logos'>
       <p id='title'><span>家</span>
       <span>計</span>
       <span>簿</span><br>
       <span>ア</span>
       <span>プ</span>
       <span>リ</span></p>
      </div>
      <div class='top-main-contents-button'>
        <ul class='button-lists'>
        <% if user_signed_in? %>
          <li><%= link_to "#{current_user.nickname}さん", new_record_path, class: 'user-nickname',id:'top-btn' %></li>
          <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'top-logout',id:'top-btn' %></li>
        <% else %>
          <li><%= link_to 'ログイン', new_user_session_path, class:'top-log-in', method: :get, id:'top-btn' %></li>
          <li><%= link_to '新規登録', new_user_registration_path, class:'top-sign-up',method: :get, id:'top-btn' %></li>
        <% end %>
        </ul>
      </div>
  </div>
</div>

app/views/records/new.html.erb
<h1>メインページ</h1>

<div class='record-multi-input'>
    <div>
      <%= form_with model:@form, url: records_path, method: :post, local: true do |form| %>
        <table>
          <thead>
            <tr>
              <th></th>
              <th class='table-top'>日付</th>
              <th class='table-top'>費目</th>
              <th class='table-top'>方法</th>
              <th class='table-top'>金額</th>
              <th class='table-top'>メモ</th>
            </tr> 
          </thead>
          <tbody>
            <%= form.fields_for :records do |f| %>
              <tr>
                <td><%= f.check_box :availability %></td>
                <td><%= f.date_field :recorded_at, class:'date-input1', id:'record-price' %></td>
                <td><%= f.collection_select(:spending_way_id,  SpendingWay.all, :id, :name, {}, {class:'select-box1', id:'record-spending-way'}) %></td>
                <td><%= f.collection_select(:spending_pay_id,  SpendingPay.all, :id, :name, {}, {class:'select-box1', id:'record-spending-pay'}) %></td>
                <td><%= f.text_field :price, class:'price-input1', id:'record-price' %></td>
                <td><%= f.text_field :description, class:'items-text1', id:'record-description' %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
          <div class='sell-btn-content1'>
          <%= form.submit '登録する' ,class:'sell-btn1', id: 'submit-save' %>
          </div>
      <% end %>
    </div>
  </div>